GET http://localhost:3000/ad

###
POST http://localhost:3000/ad
Content-Type: application/json

{
    "title": "Peugeot 206",
    "description":
      "Contrôle technique ok",
    "owner": "Julien",
    "price": 2500,
    "picture": "exemple@image.com",
    "location": "Lyon",
    "categorie_id": 2
}